<?php
    $lang['number']   = 'Faktura nr.';
    $lang['date']     = 'Betalingsdato';
    $lang['time']     = 'Tid';
    $lang['due']      = 'Sidste betalings dag';
    $lang['to']       = 'Til';
    $lang['from']     = 'Fra';
    $lang['product']  = 'Produkt';
    $lang['qty']      = 'Antal';
    $lang['price']    = 'Pris';
    $lang['discount'] = 'Rabat';
    $lang['vat']      = 'moms';
    $lang['total']    = 'Total';
    $lang['page']     = 'Side';
    $lang['page_of']  = 'af';
