<?php
    $lang['number']   = 'Rechnungsnummer';
    $lang['date']     = 'Rechnungsdatum';
    $lang['time']     = 'Rechnungs-Uhrzeit';
    $lang['due']      = 'Fälligkeitsdatum';
    $lang['to']       = 'Rechnungsempfänger';
    $lang['from']     = 'Rechnung von';
    $lang['product']  = 'Produkt';
    $lang['qty']      = 'Menge';
    $lang['price']    = 'Preis';
    $lang['discount'] = 'Rabatt';
    $lang['vat']      = 'MwSt';
    $lang['total']    = 'Gesamtbetrag';
    $lang['page']     = 'Seite';
    $lang['page_of']  = 'von';
