<?php
  $lang['number']		= 'Referenz';
  $lang['date']			= 'Rechnungsdatum';
  $lang['time']			= 'Billing time';
  $lang['due']			= 'Fälligkeitsdatum';
  $lang['to']			= 'Abrechnung';
  $lang['from']			= 'Unseren Informationen ';
  $lang['product']		= 'Produkt';
  $lang['qty']			= 'Menge';
  $lang['price']		= 'Preis';
  $lang['discount']		= 'Rabatt';
  $lang['vat']			= 'Steuer';
  $lang['total']		= 'Gesamt';
  $lang['page']			= 'Seite';
  $lang['page_of']		= 'von';
?>