<?php
    $lang['number']   = 'Number';
    $lang['date']     = 'Kuupäev';
    $lang['time']     = 'Kellaaeg';
    $lang['due']      = 'Tähtaeg';
    $lang['to']       = 'Ostja';
    $lang['from']     = 'Müüja';
    $lang['product']  = 'Toode';
    $lang['qty']      = 'Kogus';
    $lang['price']    = 'Hind';
    $lang['discount'] = 'Allah.';
    $lang['vat']      = 'KM';
    $lang['total']    = 'Kokku';
    $lang['page']     = 'Lk';
    $lang['page_of']  = '/';
