<?php
  $lang['number']		= 'RÉfÉrence';
  $lang['date']			= 'Date de facturation';
  $lang['time']			= 'Temps de facturation';
  $lang['due']			= 'Date d\'échéance';
  $lang['to']			= 'Facturation à';
  $lang['from']			= 'Nos infos';
  $lang['product']		= 'Produit';
  $lang['qty']			= 'Montant';
  $lang['price']		= 'Prix';
  $lang['discount']		= 'Réduction';
  $lang['vat']			= 'Cuve';
  $lang['total']		= 'Total';
  $lang['page']			= 'Page';
  $lang['page_of']		= 'de';
?>