<?php
    $lang['number']   = 'Référence';
    $lang['date']     = 'Date de facturation';
    $lang['time']     = 'Heure de facturation';
    $lang['due']      = 'Date d\'échéance';
    $lang['to']       = 'Facturé à';
    $lang['from']     = 'Facturé par';
    $lang['product']  = 'Produit';
    $lang['qty']      = 'Quantité';
    $lang['price']    = 'Prix unit. HT';
    $lang['discount'] = 'Réduction';
    $lang['vat']      = 'TVA';
    $lang['total']    = 'Total TTC';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'sur';
