<?php
    $lang['number']   = 'Sąskaitos numeris';
    $lang['date']     = 'Data';
    $lang['time']     = 'Laikas';
    $lang['due']      = 'Sumokėti iki';
    $lang['to']       = 'Pirkėjas';
    $lang['from']     = 'Pardavėjas';
    $lang['product']  = 'Prekės';
    $lang['qty']      = 'Kiekis';
    $lang['price']    = 'Kaina';
    $lang['discount'] = 'Nuolaida';
    $lang['vat']      = 'PVM';
    $lang['total']    = 'Suma';
    $lang['page']     = 'Puslapis';
    $lang['page_of']  = 'iš';
