<?php
    $lang['number']   = 'Referentie';
    $lang['date']     = 'Aangemaakt';
    $lang['time']     = 'Tijd';
    $lang['due']      = 'Vervaldatum';
    $lang['to']       = 'Begunstige';
    $lang['from']     = 'Onze gegevens';
    $lang['product']  = 'Product';
    $lang['qty']      = 'Aantal';
    $lang['price']    = 'Prijs';
    $lang['discount'] = 'Korting';
    $lang['vat']      = 'BTW';
    $lang['total']    = 'Totaal';
    $lang['page']     = 'Pagina';
    $lang['page_of']  = 'van de';
