<?php
    $lang['number']   = 'Nr. facturii';
    $lang['date']     = 'Data facturii';
    $lang['time']     = 'Ora facturii';
    $lang['due']      = 'Data scadenței';
    $lang['to']       = 'Client';
    $lang['from']     = 'Furnizor';
    $lang['product']  = 'Produs';
    $lang['qty']      = 'Cantitate';
    $lang['price']    = 'Preț';
    $lang['discount'] = 'Reducere';
    $lang['vat']      = 'T.V.A.';
    $lang['total']    = 'Total';
    $lang['page']     = 'Pagina';
    $lang['page_of']  = 'din';
