<?php
  $lang['number']		= 'Sklic';
  $lang['date'] 		= 'Datum obračuna';
  $lang['time']			= 'Datum zapadlosti';
  $lang['due'] 			= 'Do datuma';
  $lang['to'] 			= 'Plačnik';
  $lang['from'] 		= 'Prejemnik';
  $lang['product'] 		= 'Izdelek';
  $lang['qty'] 			= 'Količina';
  $lang['price'] 		= 'Cena';
  $lang['discount'] 	= 'Popust';
  $lang['vat'] 			= 'Davek';
  $lang['total'] 		= 'Skupaj';
  $lang['page'] 		= 'Stran';
  $lang['page_of'] 		= 'od';
?>
