<?php
    $lang['number']   = 'Faktura nr';
    $lang['date']     = 'Faktura Datum';
    $lang['time']     = 'Tid';
    $lang['due']      = 'Sista betalnings dag';
    $lang['to']       = 'Till';
    $lang['from']     = 'Från';
    $lang['product']  = 'Produkt';
    $lang['qty']      = 'Antal';
    $lang['price']    = 'Pris';
    $lang['discount'] = 'Rabatt';
    $lang['vat']      = 'moms';
    $lang['total']    = 'Totalt';
    $lang['page']     = 'Sida';
    $lang['page_of']  = 'av';
