<?php
    $lang['number']   = 'Fatura No';
    $lang['date']     = 'Fatura tarihi';
    $lang['time']     = 'Fatura zamanı';
    $lang['due']      = 'Vadesi';
    $lang['to']       = 'Firma';
    $lang['from']     = 'Müşteri';
    $lang['product']  = 'Ürün';
    $lang['qty']      = 'Adet';
    $lang['price']    = 'Fiyat';
    $lang['discount'] = 'İndirim';
    $lang['vat']      = 'Vergi';
    $lang['total']    = 'Toplam';
    $lang['page']     = 'Sayfa';
    $lang['page_of']  = 'arasında';
